### ISSUE TITLE
release / release notes: Should clean up "Roadmap", "Downloads", and "API"

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdf_tutorials#7]
- [ ] Rename "Roadmap" to "Releases", merge with Downloads somehow?
- [ ] Add a link to API Documentation once later versions are included? (or only publish for major versions???)
- [ ] API docs for 9.0.0 are broken? http://osrf-distributions.s3.amazonaws.com/sdformat/api/9.0.0/index.html
- [ ] API docs for "dev" seem old? http://osrf-distributions.s3.amazonaws.com/sdformat/api/dev/classes.html
- [ ] Add a link to Downloads if/when they're in sync with API Docs?
- [ ] Use GitHub release page?

**Comment by scpeters** [comment]
I just uploaded the 9.0.0 api docs by doing the following:

~~~
# from sdformat clone, with doxygen installed
git checkout sdformat9_9.0.0
mkdir build
cd build
cmake ..
make doc
cd doxygen/html
s3cmd sync . s3://osrf-distributions/sdformat/api/9.0.0/
~~~

**Comment by scpeters** [comment]
I think the `dev` API is copied from `6.0.0`. what do we want that to point to? should it just point to the newest tag in the list (currently 9.0.0)?

**Comment by EricCousineau-TRI** [comment]
Yeah, newest tag in the list.
Also, ideally, the newest tag overal is at the top of the list.

**Comment by scpeters** [comment]
I just updated the `dev` api to match `9.0.0`

**Comment by scpeters** [comment]
> Use GitHub release page?

I created the following issue to discuss creating releases with descriptions as part of our release process: https://github.com/ignition-tooling/release-tools/issues/195
